In [ ]:
#https://www.youtube.com/watch?v=CG3EV7UBELA

In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame(np.random.rand(10000,5),columns=('a','b','c','d','e'))

In [6]:
df.describe()

                  a             b             c             d             e
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean       0.493751      0.505957      0.500190      0.496846      0.496964
std        0.289623      0.286740      0.290858      0.287260      0.289381
min        0.000088      0.000061      0.000033      0.000032      0.000047
25%        0.242607      0.257617      0.242785      0.247775      0.243708
50%        0.489618      0.509952      0.500781      0.496663      0.497330
75%        0.742920      0.755453      0.753866      0.745423      0.744568
max        0.999813      0.999933      0.999794      0.999995      0.999921

In [8]:
for i,row in df.iterrows():
    while i < 3:
        print(f'i={i}')
        print(' ')
        print('Returned Row')
        print(row)
        print(' ')
        print(f"Column B:{row['b']}")
        print("<----------------------------->")
        print(' ')
        break

i=0

Returned Row
a    0.031043
b    0.332790
c    0.072250
d    0.221702
e    0.344741
Name: 0, dtype: float64

Column B:0.3327895542954413
<----------------------------->

i=1

Returned Row
a    0.513165
b    0.202672
c    0.571665
d    0.285358
e    0.374966
Name: 1, dtype: float64

Column B:0.20267178133551456
<----------------------------->

i=2

Returned Row
a    0.904816
b    0.510864
c    0.645803
d    0.788204
e    0.279389
Name: 2, dtype: float64

Column B:0.510863914106455
<----------------------------->

In [9]:
df.head(3)

          a         b         c         d         e
0  0.031043  0.332790  0.072250  0.221702  0.344741
1  0.513165  0.202672  0.571665  0.285358  0.374966
2  0.904816  0.510864  0.645803  0.788204  0.279389

In [11]:
def iterrow_example(df, col):
    for i,  row in df.iterrows():
        val = row[col]
        if  val <.5:
            df.at[i,col]=0
        else:
            df.at[i,col]=1

In [12]:
%timeit  iterrow_example(df,'a')

1.15 s ± 61.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [13]:
def iloc_example(df, col):
    for i in df.index:
        val = df[col].iloc[i]
        if  val <.5:
            df.at[i,col]=0
        else:
            df.at[i,col]=1

In [15]:
%timeit  iterrow_example(df,'b')

1.09 s ± 5.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [16]:
%timeit df['c']=df['c'].apply(lambda x : 0 if  x < .5 else 1)

4.31 ms ± 123 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [17]:
%timeit df['d'] = np.where(df['d'] < .5,0,1)

318 μs ± 4.16 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [18]:
%timeit df['d'] = np.where(df['d'].values < .5,0,1)

205 μs ± 5.73 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)